### ISSUE TITLE
Exception: HTTP/1.1 503 Service Unavailable

### ISSUE THREAD

**Issue by Kavita315** [iBicha/UnityYoutubePlayer#55] opened 2021-06-29 09:56 UTC
Getting Exception  In IOS build after updateing plugin to 1.3.3
<img width="616" alt="Screenshot 2021-06-29 at 3 26 27 PM" src="https://user-images.githubusercontent.com/66353708/123778075-613aed80-d8ee-11eb-99b6-439e0cab033c.png">

**Comment by iBicha** [comment] 2021-06-30 02:19
Duplicate of #39

**Closed by iBicha** 2021-06-30 02:19 UTC
