### ISSUE TITLE
360 videos cropped

### ISSUE THREAD

**Issue by badjano** [iBicha/UnityYoutubePlayer#9] opened 2020-07-01 01:23 UTC
Just tried it and the video is cropped as it was not 360, I think youtube changed something on the way 360 videos are streamed, but I´m not sure

**Comment by iBicha** [comment] 2020-07-16 05:29
Thanks for calling this out. Looks like it is the case.
I wonder if this is the case for ALL 360 videos (a.k.a the format changed for all videos) or that each video now contains more metadata on how 360 should be rendered.
In either cases, looks like a new skybox shader needs to be rewritten.

**Comment by badjano** [comment] 2020-07-16 05:58
From what I´ve seen on youtube-dl python library, it also has some other issues like audio being a separate stream, and this looks like the new 360 streaming standard, at least all videos I checked were like this... they are making it pretty hard for us

**Comment by iBicha** [comment] 2020-07-16 06:05
Having a separate stream for Audio and Video is not an issue, it was by design (because with 1080p and up, the video is available for multiple quality settings, but the audio is already at its highest quality. It would be a waste of disk space to duplicate the audio for each video quality setting, which is why a separate reusable audio stream is better, but not practical for cases like this)

**Comment by badjano** [comment] 2020-07-16 06:43
Oh, I really thought that syncing audio and video playback was going to be a pain... Also, from the youtube-dl library I found that if you send an empty user-agent, it returns equirectangular format, I don´t know if that helps

**Comment by iBicha** [comment] 2020-12-11 19:19
This will be addressed with #28 where we use youtube-dl and an empty user-agent indeed

**Comment by iBicha** [comment] 2020-12-29 17:46
This is fixed in the new version, using the empty user agent. Unfortunately, we still have an issue where the video stream and the audio stream are separated. For now, the example scene only contains the 360 video stream (no audio).

**Closed by iBicha** 2020-12-29 17:46 UTC

**Comment by badjano** [comment] 2021-05-04 06:22
@iBicha 
You probably know this by now, bit I just wasted a few hours trying to find out how to stream the audio files from 360 videos on youtube, but turns out I can´t. The formats are opus and m4a ( aac ) which are not supported in Unity. I will check later on for a dot net library that could decode it, but I´m not sure this is going to look pretty and also might get a big overhead on the cpu too.

**Comment by iBicha** [comment] 2021-05-05 04:03
> @iBicha
> You probably know this by now, bit I just wasted a few hours trying to find out how to stream the audio files from 360 videos on youtube, but turns out I can´t. The formats are opus and m4a ( aac ) which are not supported in Unity. I will check later on for a dot net library that could decode it, but I´m not sure this is going to look pretty and also might get a big overhead on the cpu too.

Thanks for digging, I guess that should have been documented here. Yes I was aware of this, it's why the sample scene with 360 video has no sound.

As a test, I tried playing the 360 video, and for the audio, I would play a low res muxed stream (video+audio) and keep the second player hidden (horrible for performance, but I was testing). I had to prepare the videos and sync to start at the same time, but they can easily get out of sync. This was not a satisfactory solution, so I left it out.

**Comment by badjano** [comment] 2021-05-05 04:21
Cool, I didn't think of that but I have to agree it's not an elegant solution but it would've been nice if it worked. I'm still betting we could somehow parse the opus sound and stream it through an audio source using OnAudioFilterRead. I'll dig into that when I have the time. Have you seen nuget extension for unity? I bet there might be something useful through that.
