### ISSUE TITLE
Exception: HTTP/1.1 400 Bad Request when trying to play a Youtube video

### ISSUE THREAD

**Issue by markdimi** [iBicha/UnityYoutubePlayer#32] opened 2021-01-29 11:11 UTC
Any idea what could be wrong? The same project was working a few days ago and now it's not.
I put the latest version(`1.3.1`) and nothing still.

> Exception: HTTP/1.1 400 Bad Request
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <9577ac7a62ef43179789031239ba8798>:0)
YoutubePlayer.YoutubeDl+<GetVideoMetaDataAsync>d__5`1[T].MoveNext () (at Library/PackageCache/com.ibicha.youtube-player@1.3.1/Runtime/YoutubeDl.cs:63)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <9577ac7a62ef43179789031239ba8798>:0)
YoutubePlayer.YoutubePlayer+<GetRawVideoUrlAsync>d__8.MoveNext () (at Library/PackageCache/com.ibicha.youtube-player@1.3.1/Runtime/YoutubePlayer.cs:52)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <9577ac7a62ef43179789031239ba8798>:0)
YoutubePlayer.YoutubePlayer+<PrepareVideoAsync>d__9.MoveNext () (at Library/PackageCache/com.ibicha.youtube-player@1.3.1/Runtime/YoutubePlayer.cs:68)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <9577ac7a62ef43179789031239ba8798>:0)
YoutubePlayer.YoutubePlayer+<PlayVideoAsync>d__10.MoveNext () (at Library/PackageCache/com.ibicha.youtube-player@1.3.1/Runtime/YoutubePlayer.cs:91)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <9577ac7a62ef43179789031239ba8798>:0)
YoutubePlayer.YoutubePlayer+<OnEnable>d__7.MoveNext () (at Library/PackageCache/com.ibicha.youtube-player@1.3.1/Runtime/YoutubePlayer.cs:39)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e414e10bfe5f45729ff122f3359de21b>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by iBicha** [comment] 2021-01-29 16:08
400 is VERY LIKELY a missing url parameter.
https://github.com/iBicha/youtube-dl-server/blob/9d0c43a4b9f8f7dba1c7a0a5615a06a8149adcaf/src/app.ts#L16

**Comment by iBicha** [comment] 2021-01-29 16:17
I'm also seeing a few HTTP 429 Too Many Requests errors on the free instance. 
I will have to provide better logging so that developers have a better idea of what's going on.

**Comment by markdimi** [comment] 2021-01-29 16:25
The missing URL makes sense, because the `Youtube` script isn't fetching the direct url to the video for the player.

**Comment by iBicha** [comment] 2021-01-30 03:29
Updated the server and published 1.3.2 to make the error message more clear. You will see the error in Unity console (missing url, too many requests, etc)
Let me know if this fixes the issue or helps narrow down the issue

**Comment by Kavita315** [comment] 2021-02-01 05:20
using version 1.3.2 plz help 

Exception: HTTP/1.1 500 Internal Server Error
ResponseError:{"error":"Command failed: /app/tools/bin/youtube-dl -f \"best\" --dump-json https://youtu.be/aJbYWaDfgf4\nERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n","stderr":"ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n","stdout":""}
<img width="1131" alt="Screenshot 2021-02-01 at 10 49 13 AM" src="https://user-images.githubusercontent.com/66353708/106417922-22a62180-647b-11eb-96e2-c642aac78220.png">

**Comment by iBicha** [comment] 2021-02-01 15:17
Closing, please reopen or create new issue if needed, thanks

**Closed by iBicha** 2021-02-01 15:17 UTC
