### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by ojy999** [iBicha/UnityYoutubePlayer#20] opened 2020-10-27 02:07 UTC
I'm not very good at this and have no idea what does this error means.
The whole description looks like this.

`KeyNotFoundException: The given key was not present in the dictionary.
System.Text.Json.JsonElement.GetProperty (System.String propertyName) (at <5542c387b88f44609b3d7ce7b1f71a4a>:0)
YoutubeExplode.ReverseEngineering.Responses.WatchPage+PlayerConfig.GetPlayerSourceUrl () (at <0c119db38ddd4963b87472d1b3ba0c1f>:0)
YoutubeExplode.Videos.Streams.StreamsClient+<GetStreamContextFromWatchPageAsync>d__4.MoveNext () (at <0c119db38ddd4963b87472d1b3ba0c1f>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
YoutubeExplode.Videos.Streams.StreamsClient+<GetManifestAsync>d__6.MoveNext () (at <0c119db38ddd4963b87472d1b3ba0c1f>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
YoutubePlayer.YoutubePlayer+<PlayVideoAsync>d__9.MoveNext () (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:63)
UnityEngine.Debug:LogException(Exception)
YoutubePlayer.<PlayVideoAsync>d__9:MoveNext() (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:80)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
YoutubeExplode.Videos.Streams.<GetManifestAsync>d__6:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
YoutubeExplode.Videos.Streams.<GetStreamContextFromWatchPageAsync>d__4:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(WatchPage)
YoutubeExplode.ReverseEngineering.Responses.<GetAsync>d__9:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(WatchPage)
YoutubeExplode.Internal.<WrapAsync>d__1`1:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(WatchPage)
YoutubeExplode.ReverseEngineering.Responses.<<GetAsync>b__0>d:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(String)
YoutubeExplode.ReverseEngineering.<GetStringAsync>d__6:MoveNext()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
`

Can someone help me out? Thank you so much.

**Comment by ahmad4zan** [comment] 2020-10-27 02:21
i think the issue is resolved in YoutubeExplode 5.1.8
https://github.com/Tyrrrz/YoutubeExplode/issues/461

@iBicha can you update the Youtube package to 5.1.8?

**Comment by ojy999** [comment] 2020-10-27 02:58
@ahmad4zan Ah, thanks for replying, although I still have no idea how to resolve it...
@iBicha need help! Thank you.

**Comment by prasetion** [comment] 2020-10-27 06:08
same issue

**Comment by ojy999** [comment] 2020-10-27 08:25
So... I tried to look for the key that it said was not present, but I've checked everywhere and everything seems to be in place and nothing is missing.

**Comment by prasetion** [comment] 2020-10-27 08:58
just like @ahmad4zan said, maybe we need to wait @iBicha update the youtube package. @ojy999 :)

**Comment by ojy999** [comment] 2020-10-27 09:05
@prasetion Seems like it... I hope he update soon tho.  (internal crying)

**Comment by jkchn** [comment] 2020-10-28 14:19
you can update it yourself by getting youtube explode and build dlls in visual studio

**Comment by kassarin** [comment] 2020-10-28 18:33
> you can update it yourself by getting youtube explode and build dlls in visual studio
> -get youtubeexplode
> -open in vs
> -build youtubeexplode (ctrl b)
> -get the dlls (YoutubeExplode-master\YoutubeExplode\bin\Debug\net461)
> -put the dlls in the plugin folder in unity (Assets>YoutubePlayer>Plugins)
> 
> i am just as clueless as you so i cant help any further. i cant believe i figured all this out by myself!

I can't seem to open the solution in VS2019. 

Can you upload the dlls to a friendly file sharing site?

**Comment by ojy999** [comment] 2020-10-29 01:42
> you can update it yourself by getting youtube explode and build dlls in visual studio
> -get youtubeexplode
> -open in vs
> -build youtubeexplode (ctrl b)
> -get the dlls (YoutubeExplode-master\YoutubeExplode\bin\Debug\net461)
> -put the dlls in the plugin folder in unity (Assets>YoutubePlayer>Plugins)
> 
> i am just as clueless as you so i cant help any further. i cant believe i figured all this out by myself!

I just did, and it's working flawlessly again!! Thank you so much!!

**Comment by kassarin** [comment] 2020-10-29 01:57
> > you can update it yourself by getting youtube explode and build dlls in visual studio
> > -get youtubeexplode
> > -open in vs
> > -build youtubeexplode (ctrl b)
> > -get the dlls (YoutubeExplode-master\YoutubeExplode\bin\Debug\net461)
> > -put the dlls in the plugin folder in unity (Assets>YoutubePlayer>Plugins)
> > i am just as clueless as you so i cant help any further. i cant believe i figured all this out by myself!
> 
> I can't seem to open the solution in VS2019.
> 
> Can you upload the dlls to a friendly file sharing site?

Nevermind, I solved this by updating VS2019. Thanks for solving this.

**Comment by prasetion** [comment] 2020-10-29 02:13
thank you everyone!!

**Comment by jkchn** [comment] 2020-10-29 23:57
i forgot to mention one very important detail that it does not build the game! atleast on my unity. try check that out @ojy999

**Comment by iBicha** [comment] 2020-12-11 19:14
This issue should be fixed now. If there's another issue, please open a separate issue. Thanks

**Closed by iBicha** 2020-12-11 19:14 UTC
