### ISSUE TITLE
Video player can't play in mobile app

### ISSUE THREAD

**Issue by jaikolek** [iBicha/UnityYoutubePlayer#112] opened 2024-04-07 12:16 UTC
I create an app using this package, in inspector and simulator seems fine. But when I build it and install it, video can't load and give error on convert link function in android logcat.

**Comment by iBicha** [comment] 2024-04-10 19:28
Duplicate of #101 
See https://github.com/iBicha/UnityYoutubePlayer/issues/96#issuecomment-1422901605

**Closed by iBicha** 2024-04-10 19:28 UTC
